syncing javadoc files
java/devjava-content pull request #109
Opened 2024-05-31 19:38 UTC by carimura

2024-06-01 15:30 UTC, ammbra approved these changes
All good here.

2024-06-01 15:57 UTC, danthe1st commented
This seems to break the JavaFX Javadocs for me (locally via Docker). For example, when clicking the `Stage` link in `JavaFX Application Basic Structure By Example` (`/learn/javafx/structure/`), it forwards me to https://download.java.net/java/GA/javafx22/@@RELEASE_UUID@@/docs/api/javafx.graphics/javafx/stage/Stage.html which is an invalid link.

2024-06-01 15:57 UTC, danthe1st requested changes
This seems to break the JavaFX Javadocs for me (locally via Docker). For example, when clicking the `Stage` link in `JavaFX Application Basic Structure By Example` (`/learn/javafx/structure/`), it forwards me to https://download.java.net/java/GA/javafx22/@@RELEASE_UUID@@/docs/api/javafx.graphics/javafx/stage/Stage.html which is an invalid link.

2024-06-01 16:03 UTC, danthe1st requested changes

2024-06-01 16:03 UTC, danthe1st commented on app/data/javafxdoc.json
> +  "javafxdoc_root":                                   "https://download.java.net/java/GA/javafx@@CURRENT_RELEASE@@/@@RELEASE_UUID@@/docs/api/",
This seems to break the JavaFX Javadocs for me (locally via Docker). For example, when clicking the `Stage` link in `JavaFX Application Basic Structure By Example` (`/learn/javafx/structure/`), it forwards me to https://download.java.net/java/GA/javafx22/@@RELEASE_UUID@@/docs/api/javafx.graphics/javafx/stage/Stage.html which is an invalid link.

2024-06-01 16:30 UTC, danthe1st commented
It seems to work now except for the `RotationTransition` link in `JavaFX Properties` (`/learn/javafx/properties/`) and I think that was missing before as well.

2024-09-25 14:04 UTC, JosePaumard approved these changes

2024-09-25 14:04 UTC, merged