fifth article in the series
java/devjava-content pull request #76
Opened 2024-03-26 16:41 UTC by venkats

2024-03-26 17:32 UTC, danthe1st requested changes
Just a few things I've noticed.

2024-03-26 17:32 UTC, danthe1st commented on app/pages/learn/01_tutorial/03_getting-to-know-the-language/03_refactoring_to_functional_style/05_converting_to_streams.md
> +	    count++;
It seems like the indentation got messed up here.

2024-03-26 17:32 UTC, danthe1st commented on app/pages/learn/01_tutorial/03_getting-to-know-the-language/03_refactoring_to_functional_style/05_converting_to_streams.md
> +Looking closely at the loop, from our discussions in the previous articles, we can recognize that the presence of `if` is a sign that we may use the `filter()` operation if we can write the code as a
This line uses two spaces after the comma which is different from other places.
Aside from that, assuming `but, where's the stream?` is a complete question, I think it should start with an uppercase letter.

2024-04-22 11:08 UTC, venkats commented
Thank you so much for the feedback. Excellent suggestions and I really appreciate them. I've make changes for each of the comments. Please let me know if you have any further suggestions. Thank you.

2024-04-22 13:19 UTC, danthe1st approved these changes

2024-04-23 22:45 UTC, carimura approved these changes

2024-04-23 22:48 UTC, carimura commented
Awesome thanks @venkats! (and @danthe1st for the review)

2024-04-23 22:48 UTC, merged